### ISSUE TITLE
Master Johns moves back to his default position after being escorted

### ISSUE THREAD

**Issue by rubyFeedback** [abalabokhin/NWNForBG#22]
In the peninsula, or what was the name ... with the prisoners,
Master Johns moves back to his default position after being escorted.

First, I escorted him to the entrance, but when I leave and go back,
he is back in his usual spawning place. If he is no longer necessary
for the game, AFTER having been escorted to the entrance, perhaps
remove him; or change his spawning place to be near the entrance
afterwards. Right now this is confusing that he was escorted, but
then returns to his default spawning place, so I think this is a 
small bug.

**Comment by abalabokhin** [comment]
Thank you, I will try to reproduce and fix it.

**Comment by abalabokhin** [comment]
Fixed in https://github.com/abalabokhin/NWNForBG/commit/9986950df82dfeb0d9c2fe9396bbfac1262b71b9
