### ISSUE TITLE
[Possible small quest glitch or quest bug] The brain parasite appears to vanish (or something)

### ISSUE THREAD

**Issue by rubyFeedback** [abalabokhin/NWNForBG#25]
So I made further progress - hopefully eventually I'll be able to do a complete run through. NWN is actually fairly big,
so it's harder to do a full run through compared to many smaller and medium-sized add-ons. Anyway.

I managed to solve the parasite quest a few days ago; Dusk was paralysed in one prison cell and I think the 
parasite tried to enter his brain. I was able to kill the parasite this time before it did so, and I could bring
the brain to Aribeth or what's her name. So I solved that part (I then failed with the undead district but that's
another issue).

For this run, though, the parasite went to the fourth prisoner and I tried to be clever and spoke with the
prisoner. The prisoner then ran away and ... the paraiste was gone. Or I could not see the parasite anymore.

Also, normally in the level before, the guard talks to me but this time he was red, aka immediately hostile.
Not sure if this affected the parasite downstairs, but the first vessel he used, also did not talk to me,
but normally talks. I then attacked him and the paraiste went to the first prison cell. Anyway.

I am not sure if there is a bug - I will retry it (oddly enough I seem to sometimes need to retry parts of
the mods; I think a few subtle things may be incorrect with the mod but it's not straightforward to find
out).

Perhaps someone could look at the logic of the paraiste, e. g. what happens if it can not find a vessel.
Should it disappear? Should the prisoner still run away? I am not sure why the parasite disappeared,
perhaps there is a check that is incorrect e. g. before it disappears (but if it enters the prisoner's
body already, the prisoner should perhaps not try to run away, but instead turn hostile - I am not
sure the parasite managed to enter, though, as I talked to the prisoner before the parasite
was right next to it).

I am just reporting this in event there is some bug, if not please just close this. I'll probably re-try that
part before the initial guard one level above turns hostile - sometimes it seems as if prior actions
influence the mod downstream responses in subtle ways (I had this impression with other mods
too, so I am trying step-wise solutions to quests nowadays rather than rush-throughs normally).

**Comment by rubyFeedback** [comment]
So quick update: I re-did that part and the guard above would talk. Then I fought the
parasite downstairs. After the fourth prisoner or so I could kill the parasite and
solve that part. Not sure if it is worth to fix the situation where the fourth (or
fifth) prisoner is killed before the parasite is trying to vanish but I am just reporting
it here. I guess it is not a bug that has to be fixed and other people can find this
issue if they have problems, so I'll close it.

**Comment by abalabokhin** [comment]
Yes, it is a known bug, but idk how to fix it. The script there is already complex enough. I asked the original content author to fix it and he told me that it is too complex. However, I have a note about it in readme:
https://github.com/abalabokhin/NWNForBG/blob/main/README.md#known-bugs

Sorry if it affected your experience too much. Good news that is it the only know bug.
