### ISSUE TITLE
Could a FAQ be added to this repository?

### ISSUE THREAD

**Issue by rubyFeedback** [abalabokhin/NWNForBG#30]
I am currently doing another play-through, and I have a few issues here and there.

I managed to solve quite some on my own, and in part using walkthroughs of the "vanilla" Neverwinter Nights. But I also run into smaller issues.

This FAQ could be split into different parts; one part may be to give slight hints.

For instance, one hint I'd like to see is how to get Oleff to trigger the dialogue option where he passes the thing needed to obtain some items, from the main crypt. Another FAQ entry would be where the main crypt is (I keep on forgetting this; I actually think I saw two crypts but my memory my fail me.) In one of the crypt, the NPC told me to visit Oleff, but when I visit Oleff, Oleff does not have a dialogue option to give permission to take something from the crypt. And I think the crypt is needed for one of the first four quests. (I'll have a look at it later today, but either way a FAQ would very much be appreciated).

The FAQ could be either directly embedded into the README, or a separate .md file perhaps, e. g. FAQ.md or FAQ/FAQ.md or faq/faq.md - something like that. (It could be on the wiki here, but the github wiki is not that elegant, and a simple .md file more than suffices, IMO. It also may be easier to maintain a FAQ file, than e. g. have things at the beamdog forum.)

**Comment by abalabokhin** [comment]
Welcome back. Actually complete walkthrough would be useful, and we have one in Russian (it might be not prefect, but it was very helpful for me). For the Oleff, I think I told you before: you need to be a priest or a paladin or have at least 10 Wis. But Oleff quest is a side quest, so even if you miss in completely, it is ok. For the other questions, I really believe that walkthrough is better here than FAQ, but I am not ready to write it down/translate it. I attached Russian walkthrough, I hope you can google translate something if you really stucked. If you can prepare proper English walkthrough, it would be awesome, but I don't have time for it now.

[NWN_For_BG_walkthrough_ru.pdf](https://github.com/user-attachments/files/15805305/NWN_For_BG_walkthrough_ru.pdf)

**Comment by abalabokhin** [comment]
I added FAQ, closing the issue.
