### ISSUE TITLE
[Small map issue I think] A chest or alter is not accessible

### ISSUE THREAD

**Issue by rubyFeedback** [abalabokhin/NWNForBG#31]
In the beggar's nest, I think, if the party goes down, there are some cultists.

There is a big room to the west, with several cultists; but to the east, and north, there is another room where I think there
is an altar. The very top-left item in that room, next to the cupboard, can not be accessed because it is blocked by something
before it. Perhaps that can be unblocked or relocated a bit on that map.

I have no idea whether it is empty or not, but it is a bit annoying that there is something that the party can not access due to the map blocking it somehow. It's probably not important though, but other containers are accessible, so this one "behaves" differently.

**Comment by abalabokhin** [comment]
Can you give me at least the area code? (press "X" in the game) and copy the area code and the mouse cursor coordinates, so I can better understand what you are talking about. But overall, there are can be something blocked for you (it can be a quest or an item you doesn't have, or didn't open yet, or is not available for you).

**Comment by abalabokhin** [comment]
I added this question and my answer to FAQ, closing the issue.
