### ISSUE TITLE
Being able to leave NeverWinter Nights against a fee

### ISSUE THREAD

**Issue by rubyFeedback** [abalabokhin/NWNForBG#32]
So I am able to solve some of the initial quests; other folks evidently got farther than me (e. g. the spider thing I haven't seen so far). Hopefully Olaf gets some improves so that I can ask him more easily about the crypt. (Ideally it could be a discoverable dialogue option; or triggered when the other NPC mentions him specifically.)

But I also thought that, meanwhile, it may be nice to be able to visit Neverwinter Nights, but also leave again. That way I could solve some parts of it, then go back to the main campaign again. Naturally in a city that is plagued and needs heroes, heroes that abandon the city are not well appreciated, so a reputation drop would be ok. Also, a fee - not sure how high it should be, say, 5000 or 10.000 or something like that? The main idea here is that the party is able to resume on the main line, even if one is not able to solve all the quests of NWN. That way I (as well as others who struggle with some parts of the mod) could also partially solve some things, but then resume with the main storyline. (If such an option already exists then perhaps it could be simplified; or made more clear as an option with the main NPC.)

At any rate, thank you for reading this and please feel free to close the issue here at any moment in time.

**Comment by abalabokhin** [comment]
There are many people, who already finished the mod, so they definetely got farther than you. For Olaf I already answered you about conditions, how you can start his quest. It is not going to be changed (I talked to the original author of this content about it). 

For the ability to leave the mod, I also don't think it is going to be implemented. The whole idea of NWN plot is that the citi has troubles and they should be solved as soon as possible. If a player leave Neverwinter, the city is probably doomed. I cannot prevent from resting for 1000 hours while in NWN content, but I don't like the idea of a player to travel to Underdark while trying to find the plague cure for Neverwinter city.

**Comment by abalabokhin** [comment]
I added this question and my answer to FAQ, closing the issue.
