### ISSUE TITLE
Bug during install (maybe compatibility error)

### ISSUE THREAD

**Issue by Schedge** [abalabokhin/NWNForBG#36]
I'm having an issue during installation - likely due to a mod conflict with either Talents of Faerun or Tweaks Anthology, but I thought it would be worth posting regardless. 

Here it the error:

ERROR: Failure("cannot append column-wise to WEAPPROF.2DA")

I have attached my full debug file in the below zip. Sorry for not posting the issue in the G3 forum - the security there does not allow for new account creation right now or support the attaching of debug files.

[SETUP-NWNFORBG.zip](https://github.com/user-attachments/files/17840400/SETUP-NWNFORBG.zip)

**Comment by abalabokhin** [comment]
What was the issue?

**Comment by Schedge** [comment]
It is difficult to replicate on a fresh install, but it seems that installing Tweaks Anthology ->IWDification-> NWN -> Talents of Faerun fixes this issue.
